<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/15Hd8td2N40Lr0omBoJ8FzRNsmeAXpEkR"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
</table>

# Basics of NumPy Arrays

Below examples shows the NumPy data manipulation to access data and subarrays, and to split, reshape, and join the arrays.

### Attributes of Array
Determining the size, shape, memory consumption, and data types of arrays

In [0]:
import numpy as np
np.random.seed(0) #seed for reproducibility
x1 = np.random.randint(10,size=6) #One-dimensional array
x2 = np.random.randint(10,size=(3,4)) #Two-dimensional array
x3 = np.random.randint(10,size=(3,4,5)) #Three-dimensional array

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [8]:
print("x3 dimension:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)

x3 dimension: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [9]:
print("x3 dtype:",x3.dtype)

x3 dtype: int64


In [10]:
print("x3 itemsize",x3.itemsize)
print("x3 nbytes",x3.nbytes)
# itemsize * size = nbytes

x3 itemsize 8
x3 nbytes 480


### Array Indexing: Accessing Single Elements

In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [12]:
x1[0]

5

In [13]:
x1[-1]

9

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[1][0]

7

In [16]:
x2[2][-2]

7

In [0]:
x2[0][0] = 2

In [18]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
# While assigning a floating point value to int data type array, the array element is slightly truncated
x1[0]=3.02848937458 

In [20]:
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Accessing Subarrays

To access the NumPy array we use the similar slicing syntax

``` python
x[start:stop:step]
```

One Dimensional Array

In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
x[4:7]

array([4, 5, 6])

In [25]:
x[::2]

array([0, 2, 4, 6, 8])

In [26]:
x[1::2]

array([1, 3, 5, 7, 9])

In [27]:
x[::-1] ## All element reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x[5::-2]

array([5, 3, 1])

### Multidimensional Subarrays
Same as one-dimensional arrays, with multiple slices separated by commas

In [29]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [30]:
x2[:2,:3]

array([[2, 5, 2],
       [7, 6, 8]])

In [31]:
x2[:3,::2]

array([[2, 2],
       [7, 8],
       [1, 7]])

In [32]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 2]])

### Accessing array rows and columns

In [33]:
x2[:,0] # First column of x2 array

array([2, 7, 1])

In [34]:
x2[0,:] # First row of x2 array

array([2, 5, 2, 4])

### Subarray as no-copy views
In NumPy the slicing doesn't create a copy. Modifying the sliced array will modify the original array

In [35]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

Let's extract a $2 \times 2$ subarray from this:

In [36]:
x2_slice = x2[:2,:2]
x2_slice

array([[2, 5],
       [7, 6]])

In [37]:
x2_slice[0,0]=99
x2_slice

array([[99,  5],
       [ 7,  6]])

In [38]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Creating copies of subarray

In [39]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [0]:
x2_sub_copy[0,0]=2

In [41]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [42]:
a = np.arange(1,10).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [44]:
a.reshape((1,3))

array([[1, 2, 3]])

In [45]:
a[np.newaxis,:]

array([[1, 2, 3]])

In [46]:
a.reshape((3,1))

array([[1],
       [2],
       [3]])

In [47]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

###Concatenation of Arrays

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [49]:
c = np.array([7,8,9])
np.concatenate([a,b,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
grid = np.array([[1,2,3],[4,5,6]])
final_grid = np.concatenate([grid,grid])
final_grid

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
grid[0,0]=2
print(final_grid)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [52]:
## Concatenate along the second axis
np.concatenate([grid,grid],axis=1)

array([[2, 2, 3, 2, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with mixed size arrays - horizontal stack ```np.hstack``` and vertical stack ```np.vstack``` is used.

In [53]:
x = np.array([1,2,3])
grid = np.array([[4,5,6],
                 [7,8,9]])
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
y = np.array([[99],
             [99]])
np.hstack([grid,y])

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [55]:
np.dstack([grid,grid])

array([[[4, 4],
        [5, 5],
        [6, 6]],

       [[7, 7],
        [8, 8],
        [9, 9]]])

### Splitting of Arrays
Array can be splitted with ```np.split```,```np.hsplit```,```np.vsplit```,and ```np.dsplit```

In [56]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [57]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
upper,lower = np.vsplit(grid,2)
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [59]:
left,right = np.hsplit(grid,2)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [60]:
y = np.random.randint(10,size=(3,4,5))
y

array([[[4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5],
        [0, 1, 5, 9, 3],
        [0, 5, 0, 1, 2]],

       [[4, 2, 0, 3, 2],
        [0, 7, 5, 9, 0],
        [2, 7, 2, 9, 2],
        [3, 3, 2, 3, 4]],

       [[1, 2, 9, 1, 4],
        [6, 8, 2, 3, 0],
        [0, 6, 0, 6, 3],
        [3, 8, 8, 8, 2]]])

Similarly ```np.dsplit``` will split the array along the third axis.
It requires atleast array of 3 dimensions.

In [61]:
d_split = np.dsplit(y,[2,2,2])
d_split

[array([[[4, 3],
         [4, 3],
         [0, 1],
         [0, 5]],
 
        [[4, 2],
         [0, 7],
         [2, 7],
         [3, 3]],
 
        [[1, 2],
         [6, 8],
         [0, 6],
         [3, 8]]]),
 array([], shape=(3, 4, 0), dtype=int64),
 array([], shape=(3, 4, 0), dtype=int64),
 array([[[4, 4, 8],
         [7, 5, 5],
         [5, 9, 3],
         [0, 1, 2]],
 
        [[0, 3, 2],
         [5, 9, 0],
         [2, 9, 2],
         [2, 3, 4]],
 
        [[9, 1, 4],
         [2, 3, 0],
         [0, 6, 3],
         [8, 8, 2]]])]