<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/1zWBmBhp4LZbh_DChzBQUJTHnT7MElG4r"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
</table>

In [0]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

50.50664653361641

The syntax is quite similar to that of NumPy's ``sum`` function, and the result is the same in the simplest case:

In [3]:
np.sum(L)

50.506646533616404

However, because it executes the operation in compiled code, NumPy's version of the operation is computed much more quickly:

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 165 ms per loop
1000 loops, best of 3: 390 µs per loop


Be careful, though: the ``sum`` function and the ``np.sum`` function are not identical, which can sometimes lead to confusion!
In particular, their optional arguments have different meanings, and ``np.sum`` is aware of multiple array dimensions, as we will see in the following section.

## Minimum and Maximum

Similarly, Python has built-in ``min`` and ``max`` functions, used to find the minimum value and maximum value of any given array:

In [5]:
min(big_array), max(big_array)

(7.464700080284103e-08, 0.9999963108225142)

NumPy's corresponding functions have similar syntax, and again operate much more quickly:

In [6]:
np.min(big_array), np.max(big_array)

(7.464700080284103e-08, 0.9999963108225142)

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 104 ms per loop
1000 loops, best of 3: 457 µs per loop


For ``min``, ``max``, ``sum``, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

In [8]:
print(big_array.min(), big_array.max(), big_array.sum())

7.464700080284103e-08 0.9999963108225142 499967.4200215392


Whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays!

### Multi dimensional aggregates

One common type of aggregation operation is an aggregate along a row or column.
Say you have some data stored in a two-dimensional array:

In [9]:
M = np.random.random((3, 4))
print(M)

[[0.01528015 0.51640405 0.39628278 0.7536491 ]
 [0.45122101 0.73066388 0.38762898 0.81467897]
 [0.37073023 0.3612448  0.58861312 0.65276395]]


By default, each NumPy aggregation function will return the aggregate over the entire array:

In [10]:
M.sum()

6.03916102306799

Aggregation functions take an additional argument specifying the *axis* along which the aggregate is computed. For example, we can find the minimum value within each column by specifying ``axis=0``:

In [11]:
M.min(axis=0)

array([0.01528015, 0.3612448 , 0.38762898, 0.65276395])

The function returns four values, corresponding to the four columns of numbers.

Similarly, we can find the maximum value within each row:

In [16]:
M.max(axis=1)

array([0.7536491 , 0.81467897, 0.65276395])