<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/1zDa3L7otvQ2j7vMrFZ2qgjYPn2xXPBIY"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
</table>

In [0]:
import numpy as np

In [0]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)

In [11]:
np.einsum('ii', a)
np.einsum(a, [0,0])
np.trace(a)

60

In [12]:
np.einsum('ii->i', a)
np.einsum(a, [0,0], [0])
np.diag(a)

array([ 0,  6, 12, 18, 24])

In [13]:
np.einsum('ij->i', a)
np.einsum(a, [0,1], [0])
np.sum(a, axis=1)

array([ 10,  35,  60,  85, 110])

In [14]:
np.einsum('...j->...', a)
np.einsum(a, [Ellipsis,1], [Ellipsis])

array([ 10,  35,  60,  85, 110])

In [15]:
np.einsum('ji', c)
np.einsum('ij->ji', c)
np.einsum(c, [1,0])
np.transpose(c)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [16]:
np.einsum('i,i', b, b)
np.einsum(b, [0], b, [0])
np.inner(b,b)

30

In [18]:
np.einsum('ij,j', a, b)
np.einsum(a, [0,1], b, [1])
np.dot(a, b)
np.einsum('...j,j', a, b)

array([ 30,  80, 130, 180, 230])

In [20]:
np.einsum('..., ...', 3, c)
np.einsum(',ij', 3, c)
np.einsum(3, [Ellipsis], c, [Ellipsis])
np.multiply(3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [21]:
np.einsum('i,j', np.arange(2)+1, b)
np.einsum(np.arange(2)+1, [0], b, [1])
np.outer(np.arange(2)+1, b)

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [23]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
np.einsum('ijk,jil->kl', a, b)
np.einsum(a, [0,1,2], b, [1,0,3], [2,3])
np.tensordot(a,b, axes=([1,0],[0,1]))

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [24]:
a = np.zeros((3, 3))
np.einsum('ii->i', a)[:] = 1
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
a = np.arange(6).reshape((3,2))
b = np.arange(12).reshape((4,3))
np.einsum('ki,jk->ij', a, b)
np.einsum('ki,...k->i...', a, b)
np.einsum('k...,jk', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

In [0]:
a = np.ones(64).reshape(2,4,8)

In [0]:
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a)

In [0]:
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='optimal')

In [0]:
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='greedy')

In [0]:
path = np.einsum_path('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='optimal')[0]
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize=path)